#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Matumoto Hayoto
# SPDX-License-Identifier: BSD-3-Clause

import sys
from math import comb

values = []
for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    try:
        values.append(int(line))
    except ValueError:
        sys.exit(1)

if len(values) != 3:
    sys.exit(1)

deck_size, desired_cards, hand_size = values

if not (0 <= desired_cards <= deck_size and 0 <= hand_size <= deck_size):
    sys.exit(1)

try:
    numerator = comb(deck_size - desired_cards, hand_size)
    denominator = comb(deck_size, hand_size)
    prob = 1 - numerator / denominator
except Exception:
    sys.exit(1)

print(prob, end="")

