#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Matumoto Hayoto
# SPDX-License-Identifier: BSD-3-Clause

import sys
from math import comb

values = []
for line in sys.stdin:
    try:
        values.append(int(line.strip()))
    except:
        continue

if len(values) != 3:
    sys.exit(1)

deck_size, desired_cards, hand_size = values

try:
    prob = 1 - comb(deck - desired, hand) / comb(deck, hand)
except:
    sys.exit(1)

print(prob)


